name: Generate xml sitemap

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1.5.0
        with:
          base-url-path: https://speechr.aboni.dev
      - name: Ping search engines
        uses: atymic/sitemap-ping-action@master
        with:
          sitemap-url: https://speechr.aboni.dev/sitemap.xml
